from . import product_attribute_value
from . import product_category
from . import product_product
from . import product_template
from . import purchase_order
from . import purchase_order_line
from . import sale_order
from . import softm_order_line_log
from . import softm_order_log
from . import stock_inventory
from . import stock_location
from . import stock_move
from . import stock_picking_type
from . import stock_picking
from . import stock_rule
from . import stock_warehouse
from . import transporter_route
from . import account_invoice_line
