{
    'name': "metro_softm_fields",
    'summary': """
        RUN-70, RUN-71, RUN-72, RUN-73, RUN-167, RUN-269, RUN-293, RUN-235,
        RUN-443, RUN-465, RUN-402, RUN-561, RUN-538, RUN-616,  RUN-650, RUN-703, RUN-767, RUN-653
        RUN-776,RUN-808,RUN-872,RUN-887,RUN-905,RUN-914,RUN-968,RUN-1033,RUN-1098, RUN-1121, RUN-1192
    """,
    'description': """
        https://jira.metrosystems.net/browse/RUN-70,
        https://jira.metrosystems.net/browse/RUN-71,
        https://jira.metrosystems.net/browse/RUN-72,
        https://jira.metrosystems.net/browse/RUN-73,
        https://jira.metrosystems.net/browse/RUN-167,
        https://jira.metrosystems.net/browse/RUN-269,
        https://jira.metrosystems.net/browse/RUN-293,
        https://jira.metrosystems.net/browse/RUN-235,
        https://jira.metrosystems.net/browse/RUN-443,
        https://jira.metrosystems.net/browse/RUN-465,
        https://jira.metrosystems.net/browse/RUN-402,
        https://jira.metrosystems.net/browse/RUN-561,
        https://jira.metrosystems.net/browse/RUN-538,
        https://jira.metrosystems.net/browse/RUN-616,
        https://jira.metrosystems.net/browse/RUN-650,
        https://jira.metrosystems.net/browse/RUN-703,
        https://jira.metrosystems.net/browse/RUN-767,
        https://jira.metrosystems.net/browse/RUN-776,
        https://jira.metrosystems.net/browse/RUN-653,
        https://jira.metrosystems.net/browse/RUN-808,
        https://jira.metrosystems.net/browse/RUN-872,
        https://jira.metrosystems.net/browse/RUN-887,
        https://jira.metrosystems.net/browse/RUN-905,
        https://jira.metrosystems.net/browse/RUN-914,
        https://jira.metrosystems.net/browse/RUN-968,
        https://jira.metrosystems.net/browse/RUN-1033,
        https://jira.metrosystems.net/browse/RUN-1098,
        https://jira.metrosystems.net/browse/RUN-1121,
        https://jira.metrosystems.net/browse/RUN-1192,
    """,
    'author': "Hucke Media GmbH & Co. KG",
    'website': "https://www.hucke-media.de",
    'category': 'Uncategorized',
    'version': '12.0.4.2.25',
    'depends': [
        'odoo_transport_management',
        'purchase',
        'sale',
        'stock',
        'stock_picking_batch',
        'metro_lot_attributes',
        'stock_change_qty_reason',
        'account',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/product_attribute_value.xml',
        'views/product_product.xml',
        'views/purchase_order_log.xml',
        'views/purchase_order.xml',
        'views/sale_order.xml',
        'views/stock_picking_type.xml',
        'views/stock_picking_batch.xml',
        'views/stock_picking.xml',
        'views/stock_warehouse.xml',
        'views/transporter_route.xml',
    ],
    'image': '',
    'license': 'AGPL-3',
}
