apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: odoo-1
  template:
    metadata:
      labels:
        app: odoo-1
    spec:
      containers:
      - name: odoofinal-sha256-1
        image: eu.gcr.io/cf-rungis-exp-development-4l/odoo:GITHUB_SHA
        ports:
        - containerPort: 8069
        volumeMounts:
        - mountPath: /mnt/filestore
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: podpvc
