{
    'name': 'Topsystem Pick by Voice',
    'version': '12.0.1.3.5',
    'summary': 'Pick by Voice Module for batch picking',
    'category': 'Warehouse',
    'author': 'Hucke Media GmBH & Co KG.',
    'maintainer': 'Thore Baden',
    'website': 'https://www.hucke-media.de/',
    'license': 'AGPL-3',
    'depends': [
        'stock',
        'stock_picking_batch'
    ],
    'data': [
        'data/res_config_settings_data.xml',
        
        'demo/stock_location_demo.xml',
        'demo/tspbv_dialoglist_demo.xml',
        'demo/tspbv_dialoglist_batch_finish.xml',
        'demo/tspbv_dialoglist_finish.xml',
        'demo/tspbv_dialoglist_hold.xml',
        'demo/tspbv_dialoglist_idle.xml',
        'demo/tspbv_dialoglist_init.xml',
        'demo/tspbv_dialoglist_location.xml',
        'demo/tspbv_dialoglist_permission.xml',
        'demo/tspbv_dialoglist_qty.xml',
        'demo/tspbv_dialoglist_session.xml',
        'demo/tspbv_workflow_demo.xml',

        'security/ir.model.access.csv',
        # 'views/resources.xml',
        'views/stock_location.xml',
        'views/stock_picking_batch.xml',
        'views/stock_picking.xml',
        'views/tspbv_dialog.xml',
        'views/tspbv_dialoglist.xml',
        'views/tspbv_input.xml',
        'views/tspbv_link.xml',

        'views/tspbv_recognition.xml',
        'views/tspbv_output.xml',
        'views/tspbv_grammar_rule_constraint.xml',
        'views/tspbv_scan.xml',
        'views/tspbv_workflow.xml',
        'views/tspbv_script.xml',
        'views/tspbv_session.xml',
        'views/tspbv_grammar_rule.xml',
        'views/res_config_settings.xml',
        'views/res_users.xml',
    ],
    'demo': [
        # 'demo/stock_location_demo.xml',
        # 'demo/tspbv_dialoglist_demo.xml',
        # 'demo/tspbv_dialoglist_finish.xml',
        # 'demo/tspbv_dialoglist_hold.xml',
        # 'demo/tspbv_dialoglist_idle.xml',
        # 'demo/tspbv_dialoglist_init.xml',
        # 'demo/tspbv_dialoglist_location.xml',
        # 'demo/tspbv_dialoglist_qty.xml',
        # 'demo/tspbv_dialoglist_session.xml',
        # 'demo/tspbv_workflow_demo.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
