# -*- encoding: utf-8 -*-

{
    'name': 'Print Barcodes from HHT',
    'version': '12.0.1.2.25',
    'summary': 'RUN-199,RUN-89,RUN-474,RUN-519,RUN-610,RUN-635,RUN-824,RUN-883,RUN-1165,RUN-1014',
    'description': """
                    RUN-199:https://jira.metrosystems.net/browse/RUN-199,
                    RUN-89:https://jira.metrosystems.net/browse/RUN-89,
                    RUN-474:https://jira.metrosystems.net/browse/RUN-474,
                    RUN-519:https://jira.metrosystems.net/browse/RUN-519,
                    RUN-610:https://jira.metrosystems.net/browse/RUN-610,
                    RUN-635:https://jira.metrosystems.net/browse/RUN-635,
                    RUN-824:https://jira.metrosystems.net/browse/RUN-824,
                    RUN-824:https://jira.metrosystems.net/browse/RUN-883,
                    RUN-1165:https://jira.metrosystems.net/browse/RUN-1165,
                    RUN-1014:https://jira.metrosystems.net/browse/RUN-1014,
                    """,
    'author': ' Cybrosys for METRONOM GmbH',
    'category': 'Metro',
    'depends': [
        'product',
        'delivery',
        'stock',
        'product_fao_fishing',
        'web_ir_actions_act_multi',
        'base_report_to_printer',
        'odoo_transport_management',
        'tis_catch_weight',
    ],
    'external_dependencies': {
        'python': ['qrcode'],
    },
    'data': [
        'report/report_lot_barcode.xml',
        'report/report_package_barcode.xml',
        'report/report_package_content.xml',
        'report/stock_report_views.xml',
        'report/report_product.xml',
        'views/inherited_stock_picking_views.xml',
        'views/res_config_settings_views.xml',
        'wizard/lot_barcode_view.xml',
        'wizard/package_barcode_view.xml',
        'wizard/package_barcode_content_view.xml',
        'wizard/product_label_view.xml',
        'data/report_paperformat_data.xml',
    ],
    'license': 'Other proprietary',
    'installable': True,
}
