{
    'name': 'Procurement Manager based on OPT',
    'version': '12.0.1.3.13',
    'summary': 'RUN-472,RUN-480,RUN-483,RUN-641,RUN-796,RUN-782,RUN-822,RUN-890,RUN-1007,RUN-1041, RUN-1048,RUN-1049',
    'description': '''
        https://jira.metrosystems.net/browse/RUN-472,
        https://jira.metrosystems.net/browse/RUN-480,
        https://jira.metrosystems.net/browse/RUN-483,
        https://jira.metrosystems.net/browse/RUN-641,
        https://jira.metrosystems.net/browse/RUN-796,
        https://jira.metrosystems.net/browse/RUN-782,
        https://jira.metrosystems.net/browse/RUN-822,
        https://jira.metrosystems.net/browse/RUN-890,
        https://jira.metrosystems.net/browse/RUN-1007,
        https://jira.metrosystems.net/browse/RUN-1041,
        https://jira.metrosystems.net/browse/RUN-1048,
        https://jira.metrosystems.net/browse/RUN-1049,
    ''',
    'category': 'Warehouse',
    'author': 'Thore Baden, Hucke Media GmbH & Co KG',
    'website': 'https://www.hucke-media.de',
    'license': 'AGPL-3',
    'depends': [
        'metro_putaway_strategy',
        'metro_lefo_cw',
        'queue_job',
    ],
    'data': [
        'data/ir_cron.xml',
        'security/stock_inventory_security.xml',
        'views/stock_picking_type.xml',
        'views/stock_picking.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
