name: Build and Deploy in GKE for production

on:
  push:
    branches:
      - production
      - dev
      - preprod

jobs:
  Deploy_to_Dev:

    runs-on: ubuntu-latest
    environment: production
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GAR_LOCATION: europe-west3
      GKE_CLUSTER: kubernetes-cluster-1    # TODO: update to cluster name
      GKE_ZONE: europe-west3-c   # TODO: update to cluster zone
      DEPLOYMENT_NAME: odoo-1 # TODO: update to deployment name
      IMAGE: odoofinal

    steps:
    - uses: actions/checkout@v3
    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker
        
