name: Build and Deploy to GKE - developer

on:
  push:
    branches:    
      - developer 

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "dev"

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


#  call-workflow:
#    uses: dhaval210/odoodev/.github/workflows/Build and Deploy on GKE.yml@dev
#    secrets: inherit
