name: Build and Deploy to GKE - dev

on:
  push:
    branches:    
      - dev
  workflow_call:

jobs:
  copy_code_in_preprod:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "preprod"

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


