name: Build and Deploy to GKE - developer

on:
  push:
    branches:    
      - developer 

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


#  call-workflow:
#    uses: dhaval210/odoodev/.github/workflows/Build and Deploy on GKE.yml@dev
#    secrets: inherit
