on:
  push:
    branches: [ "prod" ]
  workflow_call:
  
jobs:
  Deploy_to_prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Sleep for 10 seconds
      uses: dhaval210/wait-action@master
      with:
        time: '10s'
