on:
  push:
    branches:    
      - developer

jobs:
     
  Copy_code_in_preprod:
    runs-on: ubuntu-latest
    environment: copy_code_in_dev

    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "dev"
        pr_title: "Pulling ${{ github.ref }} into dev"

