on:
  push:
    branches:    
      - dev

jobs:
      
  Copy_code_in_preprod:
    runs-on: ubuntu-latest
    environment: copy_code_in_preprod
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "pp"
        pr_title: "Pulling ${{ github.ref }} into preprod"
