on:
  push:
    branches:    
      - pp

jobs:
  
  Copy_code_in_prod:
    runs-on: ubuntu-latest
    environment: copy_code_in_prod
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "prod"
        pr_title: "Pulling ${{ github.ref }} into prod"

